### ISSUE TITLE
Mac Address in API23+

### ISSUE THREAD

**Issue by GarethAyres** [GEANT/CAT-Android#1]
User has reported MAC Address in API 23+ is not longer useful, as obfuscated.
Will need to removed from UI in 23 +

**Comment by restena-sw** [comment]
Here is the corresponding Android announcement:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id
And here is some StackOverflow discussion, possibly with a viable workaround:
http://stackoverflow.com/questions/31329733/how-to-get-the-missing-wifi-mac-address-on-android-m-preview

**Comment by GarethAyres** [comment]
Hello,

I have removed displaying the MAC Address for version 23+.
https://github.com/GEANT/CAT-Android/commit/1555243a96ea4157667467a36206efbc9a7fe1df

It looks like it may be possible to get a mac address from the Extended Unique Identifier IPv6 address of an interface in Android. But this is clearly a hack, and not intended to be used this way so may not be consistent or reliable. So i haven't entertained this.

Gareth
