### ISSUE TITLE
EAP-TLS support with client certificates in config file

### ISSUE THREAD

**Issue by restena-sw** [GEANT/CAT-Android#11]
The app should support EAP-TLS: if a config file contains a client certificate and a private key, and the EAP type TLS is enabled, then all the settings should be pushed via API.

If the private key is encrypted and the passphrase is not in the config file, the app should pop up a UI question for the passphrase.

**Comment by GarethAyres** [comment]
Hello,

This enhancement is now complete and available to users in the latest release.
