### ISSUE TITLE
eduroam CAT Android app crashes on Xiaomi Honor 6X, Android 7.0

### ISSUE THREAD

**Issue by Turin86** [GEANT/CAT-Android#17]
Behaviour: the app starts with the profile search but reboots itself continuously. If user tries to change tab the app crashes.

[adb shell getprop] (excerp)

---

> [ro.build.characteristics]: [default]
> [ro.build.date]: [Mon Jan 29 22:45:43 CST 2018]
> [ro.build.date.utc]: [1517237143]
> [ro.build.description]: [BLN-L21-user 7.0 HONORBLN-L21 C432B372 release-keys]
> [ro.build.diaplay.id]: [System 5.0.0.57(16N5)]
> [ro.build.display.id]: [BLN-L21C432B372]
> [ro.build.fingerprint]: [HONOR/BLN-L21/HWBLN-H:7.0/HONORBLN-L21/C432B372:user/release-keys]
> [ro.build.flavor]: [hi6250-user]
> [ro.build.hide]: [false]
> [ro.build.hide.matchers]: [Honor;ARM;hi6250;Mali-T830;Mali-T880;]
> [ro.build.hide.replacements]: [Huawei;unknown;unknown;unknown;unknown;]
> [ro.build.hide.settings]: [4;1.2 GHz;1.0GB;405 MB;4.00 GB;540 x 960;4.3;3.0.8;2.0]
> [ro.build.host]: [WUH1000106178]
> [ro.build.hw_camera2G.enable]: [true]
> [ro.build.hw_emui_api_level]: [11]
> [ro.build.hw_emui_lite.enable]: [true]
> [ro.build.id]: [HONORBLN-L21]
> [ro.build.product]: [hi6250]
> [ro.build.subproduct]: [F2FS]
> [ro.build.tags]: [release-keys]
> [ro.build.type]: [user]
> [ro.build.update_version]: [V1_2]
> [ro.build.user]: [test]
> [ro.build.version.all_codenames]: [REL]
> [ro.build.version.base_os]: []
> [ro.build.version.codename]: [REL]
> [ro.build.version.emui]: [EmotionUI_5.0.1]
> [ro.build.version.incremental]: [C432B372]
> [ro.build.version.preview_sdk]: [0]
> [ro.build.version.release]: [7.0]
> [ro.build.version.sdk]: [24]
> [ro.build.version.security_patch]: [2018-02-01]
> 
> [ro.product.CustCVersion]: [C432]
> [ro.product.board]: [hi6250]
> [ro.product.brand]: [HONOR]
> [ro.product.cpu.abi]: [arm64-v8a]
> [ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
> [ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
> [ro.product.cpu.abilist64]: [arm64-v8a]
> [ro.product.cucc.rtsplive]: [true]
> [ro.product.device]: [HWBLN-H]
> [ro.product.fingerprintName]: [HUAWEI-BERLIN]
> [ro.product.hardwareversion]: [HL2BLNM]
> [ro.product.locale]: [en-GB]
> [ro.product.locale.language]: [en]
> [ro.product.locale.region]: [US]
> [ro.product.manufacturer]: [HUAWEI]
> [ro.product.model]: [BLN-L21]
> [ro.product.name]: [BLN-L21]
> [ro.product.platform]: [hi6250]
> [ro.product.platform.pseudonym]: [1ARB9CV]

---

[adb logcat] (just the crash)

> --------- beginning of crash
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime: FATAL EXCEPTION: main
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime: Process: uk.ac.swansea.eduroamcat, PID: 5176
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean uk.ac.swansea.eduroamcat.GEOIP.hasLocation()' on a null object reference
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at uk.ac.swansea.eduroamcat.SCAD.onPostExecute(SCAD.java:155)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at uk.ac.swansea.eduroamcat.SCAD.onPostExecute(SCAD.java:31)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.os.AsyncTask.finish(AsyncTask.java:692)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:709)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:105)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:156)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6523)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
> 03-13 10:52:19.309  5176  5176 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

I can provide more info if it's needed.

**Comment by Turin86** [comment]
Could I have some feedback on this issue please?

**Comment by GarethAyres** [comment]
Hello,

I have identified the problem and added a fix to the upcoming release of the app.

Gareth
