### ISSUE TITLE
Android 8.0: Configuration File Error, Read Error with Config File

### ISSUE THREAD

**Issue by tgy** [GEANT/CAT-Android#18]
I'm trying to set up a profile on the Android app eduroam CAT.

I'm using Android 8.0 and I'm trying to install the corresponding Android 8.0 Oreo profile downloaded from [this page](https://cat.eduroam.org/?idp=982&profile=3906).

When in the application, I'm using the drop-down menu and clicking "Select Config File". Then I select the downloaded profile.

When I do this I get a "Configuration File Error" and "Read Error with Config File".

I don't know what to do here.

eduroamCAT version is 1.1.44

**Comment by GarethAyres** [comment]
Hello,

I have tried to repeat this error on my emulator of Android 8.0, without success.

![screenshot_1531921342](https://user-images.githubusercontent.com/329527/42885481-fbfc7bc4-8a98-11e8-8250-0543555c705c.png)

I have tried manually selecting the downloaded profile and discovering the profile.

What device type/model are you using?

Thanks,
Gareth

**Comment by GarethAyres** [comment]
No response from user, so closing issue.

Gareth
