### ISSUE TITLE
Problem downloading configuration file

### ISSUE THREAD

**Issue by fescalero** [GEANT/CAT-Android#21]
When I select to download "Universidad Rey Juan Carlos" configuration file, appear an error reading this file. ¿Any suggestion?

**Comment by restena-sw** [comment]
For which operating system was that?

**Comment by fescalero** [comment]
Sorry,
Android 8.0.0 at Huawei P10

**Comment by fescalero** [comment]
When the error appears, you can go to the web and download and install the file correctly using the app.

**Comment by restena-sw** [comment]
Ok, we've had more than one report about this. I believe the developer is already aware.

**Comment by GarethAyres** [comment]
Hello,

I believe i have resolved this issue with the latest build. But it is not yet available to users. I am hoping to publish it next week, I will update this issue when i do for you to test.
Gareth

**Comment by GarethAyres** [comment]
Hello,
The latest release is available to users now, so i believe this issue is resolved, I will close it now until i hear differently.

**Comment by javich-dev** [comment]
we need to open again this issue.
When I select to download "Universidad Rey Juan Carlos" configuration file, appear an error reading this file. ¿Any suggestion?
![Screenshot_2019-08-02-12-00-46](https://user-images.githubusercontent.com/54804218/64113384-74301580-cd8a-11e9-82ed-5b640f6358c5.png)

**Comment by javich-dev** [comment]
thanks in advance

**Comment by restena-sw** [comment]
Data point: the user wrote in another issue that he sees the issue on Huawei devices with Android 7 only.
With an Android 7 on a Samsung device, I see no issues with the configuration profile of Rey Juan Carlos.

**Comment by restena-sw** [comment]
Addendum: the exact devices were:

    Huawei Media Pad M3
    Huawei P10
