### ISSUE TITLE
android 10  certificates

### ISSUE THREAD

**Issue by dkwo** [GEANT/CAT-Android#44]
Not sure this is a bug, but if I uninstall the app, also the certificate and eduroam profile are gone: is this the intended behavior?

More to the point, it seems I'm unable to just configure eduroam *with* certificate on Android 10, is this also known? I'm using  a .pem file as certificate from my uni, but cannot find the corresponding field where to put `radiusauth...` as in WPA on Linux (I guess it's not `Domain`, right?)

Thanks.

**Comment by restena-sw** [comment]
On recent versions of Android, this is indeed the behaviour Android devs intended :-/

Nothing in our code binds the configuration to the app, but as Android code evolved, the operating system at some point started doing that.

From the top of my head, I do not know the exact version when this was introduced any more.

FWIW, Android 11 changes the entire API set and we will probably launch a whole new app to support the new approach.

**Comment by restena-sw** [comment]
When it comes to your second part of the question: a PR for the app should be about issues with the app, not about issues /without/ the app ;-)

FWIW, you'll need to install the PEM file into the "Wi-Fi Store", not the "VPN and Apps" store. Once it's in the Wi-Fi store, it should become visible in the drop-down list for CAs.

Domain is the name of your authentication server, as communicated to you by your network admin.

**Comment by restena-sw** [comment]
Nothing to be done in terms of code here.

**Comment by dkwo** [comment]
> Domain is the name of your authentication server, as communicated to you by your network admin.

I see, thanks.
