### ISSUE TITLE
Profile failes to install due to "A screen lock is required", while a screen lock is present

### ISSUE THREAD

**Issue by GeorgiosDR** [GEANT/CAT-Android#48]
Suddenly cateduroam refuses to install a profile, and complains that no screen lock is present. I have tried with different levels of security for screen locks, but with no avail. Something is broken.

The problem is on my Galaxy S20 5G SM-G981B/DS
Samsung One UI 5.1
Android 13
Kernel 4.19.87-26203352

**Comment by restena-sw** [comment]
Android versions  above 8 should not use this app. Use "geteduroam" instead.
