### ISSUE TITLE
unhandled NumberFormatException due to EAP-Metadata containing localized coordinates

### ISSUE THREAD

**Issue by zmousm** [GEANT/CAT-Android#5]
eduroam CAT may present EAP-Metadata which apparently may contain localized coordinates; in some locales (for example Greek) this means decimal separator is a `COMMA` rather than a `FULL STOP`. Since `EAPMetadata.parseProfile()` [uses `Double.parseDouble()`](https://github.com/GEANT/CAT-Android/blob/master/src/uk/ac/swansea/eduroamcat/EAPMetadata.java#L631) to parse `ProviderLocation` coordinates, which is not locale-aware, and it does not catch a `NumberFormatException` that may be thrown, the CAT-Android application crashes when presented with such a profile.

Here is the crash log:
```
--------- beginning of crash
E/AndroidRuntime( 3138): FATAL EXCEPTION: main
E/AndroidRuntime( 3138): Process: uk.ac.swansea.eduroamcat, PID: 3138
E/AndroidRuntime( 3138): java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.ac.swansea.eduroamcat/uk.ac.swansea.eduroamcat.EAPMetadata}: java.lang.NumberFormatException: Invalid double: "38,6321"
E/AndroidRuntime( 3138): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 3138): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 3138): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 3138): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 3138): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3138): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3138): 	at android.app.ActivityThread.main(ActivityThread.java:5258)
E/AndroidRuntime( 3138): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3138): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3138): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 3138): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 3138): Caused by: java.lang.NumberFormatException: Invalid double: "38,6321"
E/AndroidRuntime( 3138): 	at java.lang.StringToReal.invalidReal(StringToReal.java:63)
E/AndroidRuntime( 3138): 	at java.lang.StringToReal.initialParse(StringToReal.java:164)
E/AndroidRuntime( 3138): 	at java.lang.StringToReal.parseDouble(StringToReal.java:282)
E/AndroidRuntime( 3138): 	at java.lang.Double.parseDouble(Double.java:301)
E/AndroidRuntime( 3138): 	at uk.ac.swansea.eduroamcat.EAPMetadata.parseProfile(EAPMetadata.java:643)
E/AndroidRuntime( 3138): 	at uk.ac.swansea.eduroamcat.EAPMetadata.onCreate(EAPMetadata.java:156)
E/AndroidRuntime( 3138): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 3138): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 3138): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 3138): 	... 10 more
```
And here is an EAP-Metadata document which triggers this bug:
https://gist.github.com/zmousm/a5f2a7b680275a770aa60d0be47497f5
It was downloaded from:
https://cat.eduroam.org/user/API.php?action=downloadInstaller&lang=el&id=android_lollipop&profile=2811

**Comment by restena-sw** [comment]
I believe coordinates should not be localised in the XML output in the first place, so this is rather an eduroam CAT bug, not the app's.
I'll open a bug at CAT instead.

**Comment by zmousm** [comment]
I still think it would be a good idea to catch such exceptions though in any case.

**Comment by restena-sw** [comment]
I think the XML file would actually fail XML schema validity as it supposedly contains an integer. Rather than being gentle on individual values, the correct treatment would be to validate the XML on incoming, and throw an error if it fails to validate.
I'm reopening the bug with that new scope.

**Comment by zmousm** [comment]
Does the schema define such elements as decimal?

**Comment by restena-sw** [comment]
The current rev does:
  <xs:simpleType name="gps-coordinate">
    <xs:annotation>
      <xs:documentation>
        GPS coordinate for one axis; degrees and metric minutes
      </xs:documentation>
    </xs:annotation>

    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="7"/>
    </xs:restriction>
  </xs:simpleType>

Earlier versions did as well; I don't recall if the -00 version that is currently used by the app also already did (but am inclined to think so).

In any case, the app is expected to update to the newest spec at some point soon, so I don't worry that much about the old one.

**Comment by GarethAyres** [comment]
I will certainly push a fix to catch the exception. We dont want the app crashing even with bad input.

Ill look to do this asap today. 

Thanks for providing such a detailed report on the problem. Makes writing a fix much easier.

**Comment by zmousm** [comment]
Thanks @GarethAyres 

@restena-sw can you provide btw to the location for the current EAP-Metadata schema?

**Comment by restena-sw** [comment]
I'll send you the list via mail. The repo with the IETF draft and resulting YANG and XSD files is still in a GEANT SVN repo catching dust; will convert to GitHub soon.

**Comment by GarethAyres** [comment]
I have pushed a fix to GitHub for this, and tested and released a new app in the Play store.

Closing this issue.

Gareth.
